import { readFile, writeFile } from "node:fs/promises";

const wasm = await readFile(new URL("../wasm/haya32x64.wasm", import.meta.url));
const base64 = wasm.toString("base64");
const chunks = [];
for (let i = 0; i < base64.length; i += 72) {
	chunks.push(`\t"${base64.slice(i, i + 72)}"`);
}

const source = `// Generated by scripts/embed.mjs from wasm/haya32x64.wasm.
// The module compiles the reference C header and is ${wasm.length} bytes.
export const wasmBase64 = [
${chunks.join(",\n")},
].join("");
`;

await writeFile(new URL("../wasm-module.js", import.meta.url), source);
